# Generated by Django 5.0.4 on 2024-04-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_remove_task_assigned_to_remove_task_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
    ]
